version: "3.8"

services:
  # Angular Sandbox
  # ng-nx-sandbox:
  #   extends:
  #     file: docker-compose.base.yml
  #     service: ng-nx-sandbox-base
  #   command: npm run dev:sandbox
  #   ports:
  #     - "4200:4200"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  # UI Library
  sandbox-ui:
    extends:
      file: docker-compose.base.yml
      service: ng-nx-sandbox-base
    command: npm run storybook:run
    ports:
      - "4400:4400"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Angular Pet Rescue Mgmt App
  pet-rescue-mgmt-ui:
    extends:
      file: docker-compose.base.yml
      service: ng-nx-sandbox-base
    command: npm run dev:pet-rescue-mgmt
    ports:
      - "4444:4444"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # API for Pet Rescue Mgmt App
  pet-rescue-mgmt-api:
    extends:
      file: docker-compose.base.yml
      service: ng-nx-sandbox-base
    command: npm run api:pet-rescue-mgmt
    environment:
      - MONGO_URI=mongodb://mongo:27017/pets-mgmt
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  # mock-rest-api:
  #   extends:
  #     file: docker-compose.base.yml
  #     service: ng-nx-sandbox-base
  #   command: npm run mock:api
  #   ports:
  #     - "3000:3000"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

volumes:
  mono-node-modules: null
  mongodata: