version: '3'

services:
  # Angular Application
  ng-nx-sandbox:
    extends:
      file: docker-compose.base.yml
      service: ng-nx-sandbox-base
    command: npm run dev
    ports:
      - "4200:4200"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # UI Library
  sandbox-ui:
    extends:
      file: docker-compose.base.yml
      service: ng-nx-sandbox-base
    command: npm run storybook:run
    ports:
      - "4400:4400"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pet-app-api:
    extends:
      file: docker-compose.base.yml
      service: ng-nx-sandbox-base
    command: npm run api:pet-app
    environment:
      - MONGO_URI=mongodb://mongo:27017/pets
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mock-rest-api:
    extends:
      file: docker-compose.base.yml
      service: ng-nx-sandbox-base
    command: npm run mock:api
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mono-node-modules: null